export interface PropsDataResume {
    color?: string ;
    locale?: string ;
    personalDetails?: Record<string, string |  undefined> ;
    position?: string ;
    sectionsOrder?: string[] ;
    customSections?: object[];
    sectionTitles?: object ;
    visibleAvatar?: boolean ;
    avatar?: Record<string, string | boolean | undefined> | null ;
    spacing?: string ;
    visibleReferences?: boolean ;
    hideSkillLevel?: boolean ;
    isCreativeStyle?: boolean ;
    opacityProfile?: string ;
    opacityPosition?: string ;
    opacityPersonalDetails?: string ;
    opacitySkills?: string ;
    opacityLanguages?: string ;
    opacityWorkExperiences?: string ;
    opacityEducations?: string ;
    listColors?: string[];
    hobbies?: string;
    workExperiences?: Array<Record<string, string | number | boolean | undefined>>;
    educations?: Array<Record<string, string | number | undefined>>;
    certifications?: Array<Record<string, string | number | undefined>>;
    skills?: Array<Record<string, string | number | undefined>>;
    references?: Array<Record<string, string | number | undefined>>;
    courses?: object[];
    activities?: object[];
    internships?: object[];
    languages?: Array<Record<string, string | number | undefined>>;
    email?: string;
    step?: number;
    resume_applications?: object[];
    id?: string;
    template?: string;
    rootTemplate?: string;
    profile?: string;
    title?: string;
}
